name: Build Pipeline to Dev New

on:          
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
      - 'badges/*'
      - 'pom.xml'
      - '*.svg'
      - '*.json'
      - '*.md'
  workflow_dispatch:
  
env:
  #default is develop
  SOURCECODE_MANAGE_BRANCH: master
  SOURCECODE_HOME_PATH: api-demo-java8
  #GITLAB_REPO: git.g-able.com/ais-esaving/service-a.git
    
  #POM_VERSION_LINE_NUMBER: 8
  
  #SONAR_PROJECT_KEY: api-demo-java8
  
  #DOCKER_IMAGE_NAME: api-demo-java8
  
  GITOPS_MANAGE_BRANCH: develop
  GITOPS_APP_NAME: api-demo-java8
  
  
jobs:
  generate-version:
    runs-on: ubuntu-latest
    environment: develop
    
    steps:
      - name: "Prepare Configuration" 
        uses: e-saving/birdtest-template-cicd/Dev/PrepareConfigurationAction@main
        with: 
          gitops_repo: e-saving/gitops_deployment
          gitops_manage_branch: develop
          gitops_token: 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
          gitops_app_name: api-demo-java8
      
     
